{
  "language": "node_js",
  "os": [
    "linux"
  ],
  "sudo": false,
  "branches": {
    "only": [
      "master"
    ]
  },
  "cache": {
    "npm": true
  },
  "node_js": [
    "12"
  ],
  "before_script": [
    "npm install hexo-cli"
  ],
  "script": [
    "hexo clean",
    "hexo generate"
  ],
  "deploy": [
    {
      "provider": "pages",
      "on": {
        "branch": [
          "master"
        ]
      },
      "skip_cleanup": true,
      "token": "$GITHUB_TOKEN",
      "local_dir": "public",
      "keep_history": false
    }
  ]
}