language: node_js

sudo: false

branches:
  only:
  - master

cache:
  - npm

node_js:
  - "12"

before_script:
  - npm install hexo-cli

script:
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  keep-history: false
  on:
    branch: master